# Module 2: High-Performance Computing with NumPy
## Goal: Transforming loops into high-speed vectorized operations.

In this notebook, we will prove that NumPy's architecture is the only way to handle 
"Big Data" in Python. We will explore how **Vectorization** and **Broadcasting** eliminate the need for slow Python loops.

### Vectorization: The Speed Engine
We define **Vectorization** as the process of replacing explicit loops with 
array expressions.

**Task**: Calculate the square of 1 million numbers.

In [1]:
import numpy as np
import time

# Create 1 million data points [cite: 151]
size = 1_000_000
data_list = list(range(size))
data_array = np.arange(size)

# 1. Standard Python Loop
start = time.time()
loop_result = [x**2 for x in data_list]
print(f"Loop duration: {time.time() - start:.5f} seconds")

# 2. NumPy Vectorized Operation 
start = time.time()
vector_result = data_array**2
print(f"Vectorized duration: {time.time() - start:.5f} seconds")

Loop duration: 0.41692 seconds
Vectorized duration: 0.00379 seconds


### Broadcasting: Operations on Different Shapes
Broadcasting follows strict rules:
1. If the arrays have different ranks, prepend the shape of the smaller array with 1s.
2. The arrays are compatible if they have the same size in a dimension, or if one is 1.

Example: Adding a scalar to a matrix.
$$A + b = \begin{bmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{bmatrix} + b = \begin{bmatrix} a_{11}+b & a_{12}+b \\ a_{21}+b & a_{22}+b \end{bmatrix}$$

In [2]:
matrix = np.array([[10, 20], [30, 40]])
scalar = 5

# The scalar is "broadcasted" to match the (2,2) shape of the matrix
print("Result of Broadcasting:\n", matrix + scalar)

Result of Broadcasting:
 [[15 25]
 [35 45]]


### Navigating Numerical Grids
We can pull complex patterns (like every second row, or only specific coordinates) 
from massive grids.

In [3]:
grid = np.random.randint(1, 100, (5, 5))
print("Original Grid:\n", grid)

# Slicing: Get the first 3 rows and last 2 columns 
subset = grid[:3, -2:]
print("\nSubset:\n", subset)

# Fancy Indexing: Get elements at specific indices 
rows = [0, 2, 4]
cols = [1, 3, 0]
print("\nSelected Elements:", grid[rows, cols])

Original Grid:
 [[87 60 37 23 59]
 [47 11 36 53 66]
 [64 86 26 92 69]
 [77 50 89 50 78]
 [38 37  4 89 70]]

Subset:
 [[23 59]
 [53 66]
 [92 69]]

Selected Elements: [60 92 38]


### Mathematical Power & Simulations
NumPy provides `ufuncs` that apply complex math instantly. 
We also use `np.random` to create synthetic test environments.

In [4]:
# Generate synthetic data (e.g., 1000 temperature readings) 
temps = np.random.normal(loc=25, scale=5, size=1000)

# Apply a Log transformation to normalize skewed data 
log_temps = np.log(temps)

print(f"Mean Temperature: {np.mean(temps):.2f}")
print(f"Standard Deviation: {np.std(temps):.2f}")

Mean Temperature: 25.23
Standard Deviation: 5.11


### Student Exercise: The "High-Speed Matrix Engine"
**Goal**: Solve the formula $Y = (X^2 + 10) / 2$ for 1 million points without a loop.
1. Generate 1 million random integers between 1 and 500.
2. Apply the formula using Vectorization.
3. Use a Boolean mask to filter only results where $Y > 100$.